version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: user_db
    environment:
     - MYSQL_ROOT_PASSWORD={password}
     - MYSQL_DATABASE={Database}
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - springboot-mysql-net

  springboot-app:
    image: springboot-app
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/{database}?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
      - SPRING_DATASOURCE_USERNAME={username}
      - SPRING_DATASOURCE_PASSWORD={password}
    networks:
      springboot-mysql-net:

networks:
  springboot-mysql-net:

volumes:
  mysql_data:
